### ISSUE TITLE
Why am i getting this error message?

### ISSUE THREAD

**Issue by jonaspijnenburg** [studioimaginaire/phue#23] opened 2014-02-27 09:09 UTC
Hi guys!

Thank you very much for this amazing library. It has helped me use my philips hue trough a raspberry pi even though i didn't have experience using either. 

One problem i have is after running my hue program for about a minute is the following error. I have no clue why this comes. In my program i change the hue and the brightness trough 'brivar' and 'huevar'. 

In this error message it's because of brivar. in other error messages i get it's about the huevar.

"
Traceback (most recent call last):
  File "v3.py", line 130, in <module>
    b.set_light(2,'bri', brivar)
  File "/usr/local/lib/python2.7/dist-packages/phue.py", line 611, in set_light
    converted_light) + '/state', json.dumps(data)))
  File "/usr/local/lib/python2.7/dist-packages/phue.py", line 430, in request
    result = connection.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1034, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
"

The philips developer website tells me you can send about 10 commands to lights per second so i can't imagine that it is because i overload the lamps.

Kind regards,
Jonas

**Comment by lleevveell66** [comment] 2015-05-22 14:57
This also happens for me, after a random, but lengthy amount of time.  Here is my script:

```python
#!/usr/bin/python

from phue import Bridge
import random,time

b=Bridge('192.168.44.171')

light_names=b.get_light_objects('name')
light_ids=b.get_light_objects('id')

#names=['Studio Desk Lamp', 'Studio Clip Lamp', 'Fireplace Spot',
#       'Master Lamp', 'LivingColors 1', 'LivingColors 2']
names=['Studio Desk Lamp', 'Studio Clip Lamp', 'Fireplace Spot',
       'LivingColors 1', 'LivingColors 2']

delay=30

while 1:
  saturation=random.randint(200,255)                    # 0-255
  hue=random.randint(1,65534)                           # 0-65535
  brightness=random.randint(1,254)                      # 0-255

  for lightname in names:
    light=light_names[lightname]
    light.transitiontime=delay                          # 0-300 (0-30 seconds)
    light.brightness=brightness
    light.saturation=saturation
    light.hue=hue

  time.sleep(delay/10)

exit(0)
```

You might have it let it run a day or so to reproduce.  

```
root@lie-pi5:/usr/local/src/raymond/hueslapper-0.0.1# ./hueslapper
Traceback (most recent call last):
  File "./hueslapper", line 32, in <module>
    light.hue=hue
  File "/usr/local/lib/python2.7/dist-packages/phue-0.8-py2.7.egg/phue.py", line 192, in hue
    self._set('hue', self._hue)
  File "/usr/local/lib/python2.7/dist-packages/phue-0.8-py2.7.egg/phue.py", line 106, in _set
    return self.bridge.set_light(self.light_id, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/phue-0.8-py2.7.egg/phue.py", line 684, in set_light
    converted_light) + '/state', json.dumps(data)))
  File "/usr/local/lib/python2.7/dist-packages/phue-0.8-py2.7.egg/phue.py", line 469, in request
    result = connection.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1034, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
root@lie-pi5:/usr/local/src/raymond/hueslapper-0.0.1#
```

**Comment by lleevveell66** [comment] 2015-05-22 15:07
I will add that the above code was changed, and I am re-running it to test.  I changed the limits of the random numbers.  They were set to (0,65535) on hue and (0,255) on brightness.  I figured it might be a matter of not understanding the minimum and maximum allowed values in your library.  I got those limits from another web page, because I could not find them in your documentation.  I will let you know if the problem still occurs using (1,65534) and (1,254) tighter limits.

**Comment by lleevveell66** [comment] 2015-05-22 16:20
```
root@lie-pi5:/usr/local/src/raymond/hueslapper-0.0.1# ./hueslapper
Traceback (most recent call last):
  File "./hueslapper", line 27, in <module>
    light.saturation=saturation
  File "/usr/local/lib/python2.7/dist-packages/phue-0.8-py2.7.egg/phue.py", line 207, in saturation
    self._set('sat', self._saturation)
  File "/usr/local/lib/python2.7/dist-packages/phue-0.8-py2.7.egg/phue.py", line 106, in _set
    return self.bridge.set_light(self.light_id, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/phue-0.8-py2.7.egg/phue.py", line 684, in set_light
    converted_light) + '/state', json.dumps(data)))
  File "/usr/local/lib/python2.7/dist-packages/phue-0.8-py2.7.egg/phue.py", line 469, in request
    result = connection.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1034, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
root@lie-pi5:/usr/local/src/raymond/hueslapper-0.0.1#
```

No dice.  This only ran about an hour.

**Comment by natcl** [comment] 2015-05-22 18:09
Did you enable debugging to see what the bridge responds ?

**Comment by lleevveell66** [comment] 2015-05-23 18:52
No.  I did not realize there was debugging/verbose mode available.  How do I do that?  I'll check the readme.

Just an update - I made a wrapper script to keep it running, and while I was at it, I logged times it restarted.  Here is the wrapper script

```
#!/bin/sh

touch slap.log

while true; do
  TIMESTAMP=`date '+%D %T'`
  echo "*** HueSlapper starting at $TIMESTAMP ***" >> slap.log
  ./hueslapper
  echo EXIT STATUS WAS $? >> slap.log
done

exit 0
```

And, here are the times it occured, after running a few hours:

```
root@lie-pi5:/usr/local/src/raymond/hueslapper-0.0.1# cat slap.log
*** HueSlapper starting at 05/23/15 11:31:19 ***
EXIT STATUS WAS 1
*** HueSlapper starting at 05/23/15 12:12:14 ***
EXIT STATUS WAS 1
*** HueSlapper starting at 05/23/15 12:57:42 ***
EXIT STATUS WAS 1
*** HueSlapper starting at 05/23/15 13:42:10 ***
```

So, I do almost see a 45-minute pattern, here.  I will begin checking my network to see if I can find anything goofy happening every 45 minutes.  I will also let this run all day to try to get more of a pattern.  I will also enable debugging, if I can find it.  I assume you mean there are debug levels in your library?

**Comment by lleevveell66** [comment] 2015-05-23 18:59
Found it in the CHANGELOG:

"Logging level can be set at init: b = Bridge(logging = 'debug') (Nathanaël Lécaudé)"

Is that what you mean?

**Comment by lleevveell66** [comment] 2015-05-23 19:02
This seemed to work, for others' future reference:

```
b=Bridge('192.168.44.171')
b.logging=('debug')
```

I assume this will log to the console?

**Comment by natcl** [comment] 2015-05-23 19:20
yes !

**Comment by natcl** [comment] 2015-05-23 19:23
Actually that was changed I think. If you look at the bottom of the phue.py file you will see how to do it. You simply need to add this:
´´´python
logging.basicConfig(level=debug)
´´´

**Comment by lleevveell66** [comment] 2015-05-23 19:40
Cool, thanks.  That led me to finding out how.  Here is the new script which I will run the rest of today:

```python
#!/usr/bin/python

from phue import Bridge
import random,time,logging

b=Bridge('192.168.44.171')
b.logging=('debug')

logging.basicConfig(filename='hueslapper.log',level=logging.DEBUG)

light_names=b.get_light_objects('name')
#light_ids=b.get_light_objects('id')

names=['Studio Desk Lamp', 'Studio Clip Lamp', 'Fireplace Spot',
       'LivingColors 1', 'LivingColors 2']

for lightname in names:
 b.set_light(lightname, 'on', True)

delay=30

while 1:
  saturation=random.randint(200,255)                    # 0-255
  hue=random.randint(1,65534)                           # 0-65535
  brightness=random.randint(1,254)                      # 0-255

  for lightname in names:
    light=light_names[lightname]
    light.transitiontime=delay                          # 0-300 (0-30 seconds)
    light.brightness=brightness
    light.saturation=saturation
    light.hue=hue

  time.sleep((delay/10)+1)

exit(0)
```

The hueslapper.log file is being populated with entries, so this works well.

**Comment by lleevveell66** [comment] 2015-05-23 20:57
I'm afraid the debugging is not going to help.  There is no timestamping on the debug logs, and there are a zillion entries between failures, due to sending this every 30 seconds on several lights.  I am able to search the log on "swversion" to find the entries when the script has restarted, since that is one of the first things it does, before changing light values.  Here is what I am seeing just before the first failure:

```
.
.
DEBUG:phue:PUT /api/1ef1d146dae80a72ad098aa21a675db/lights/2/state {"transitiontime": 30, "hue": 39458}
DEBUG:phue:[{"success":{"/lights/2/state/transitiontime":30}},{"success":{"/lights/2/state/hue":39458}}]
DEBUG:phue:[[{u'success': {u'/lights/2/state/transitiontime': 30}}, {u'success': {u'/lights/2/state/hue': 39458}}]]
DEBUG:phue:Setting with transitiontime = 30 ds = 3.0 s
DEBUG:phue:{'transitiontime': 30, 'bri': 99}
DEBUG:phue:PUT /api/1ef1d146dae80a72ad098aa21a675db/lights/15/state {"transitiontime": 30, "bri": 99}
DEBUG:phue:[{"success":{"/lights/15/state/transitiontime":30}},{"success":{"/lights/15/state/bri":99}}]
DEBUG:phue:[[{u'success': {u'/lights/15/state/transitiontime': 30}}, {u'success': {u'/lights/15/state/bri': 99}}]]
DEBUG:phue:Setting with transitiontime = 30 ds = 3.0 s
DEBUG:phue:{'transitiontime': 30, 'sat': 244}
DEBUG:phue:PUT /api/1ef1d146dae80a72ad098aa21a675db/lights/15/state {"transitiontime": 30, "sat": 244}
DEBUG:phue:[{"success":{"/lights/15/state/transitiontime":30}},{"success":{"/lights/15/state/sat":244}}]
DEBUG:phue:[[{u'success': {u'/lights/15/state/transitiontime': 30}}, {u'success': {u'/lights/15/state/sat': 244}}]]
DEBUG:phue:Setting with transitiontime = 30 ds = 3.0 s
DEBUG:phue:{'transitiontime': 30, 'hue': 29727}
DEBUG:phue:PUT /api/1ef1d146dae80a72ad098aa21a675db/lights/15/state {"transitiontime": 30, "hue": 29727}
DEBUG:phue:[{"success":{"/lights/15/state/transitiontime":30}},{"success":{"/lights/15/state/hue":29727}}]
DEBUG:phue:[[{u'success': {u'/lights/15/state/transitiontime': 30}}, {u'success': {u'/lights/15/state/hue': 29727}}]]
DEBUG:phue:Setting with transitiontime = 30 ds = 3.0 s
DEBUG:phue:{'transitiontime': 30, 'bri': 99}
DEBUG:phue:PUT /api/1ef1d146dae80a72ad098aa21a675db/lights/16/state {"transitiontime": 30, "bri": 99}
DEBUG:phue:[{"success":{"/lights/16/state/transitiontime":30}},{"success":{"/lights/16/state/bri":99}}]
DEBUG:phue:[[{u'success': {u'/lights/16/state/transitiontime': 30}}, {u'success': {u'/lights/16/state/bri': 99}}]]
DEBUG:phue:Setting with transitiontime = 30 ds = 3.0 s
DEBUG:phue:{'transitiontime': 30, 'sat': 244}
DEBUG:phue:PUT /api/1ef1d146dae80a72ad098aa21a675db/lights/16/state {"transitiontime": 30, "sat": 244}
DEBUG:phue:[{"success":{"/lights/16/state/transitiontime":30}},{"success":{"/lights/16/state/sat":244}}]
DEBUG:phue:[[{u'success': {u'/lights/16/state/transitiontime': 30}}, {u'success': {u'/lights/16/state/sat': 244}}]]
DEBUG:phue:Setting with transitiontime = 30 ds = 3.0 s
DEBUG:phue:{'transitiontime': 30, 'hue': 29727}
DEBUG:phue:PUT /api/1ef1d146dae80a72ad098aa21a675db/lights/16/state {"transitiontime": 30, "hue": 29727}
DEBUG:phue:GET /api/1ef1d146dae80a72ad098aa21a675db/lights/ None
DEBUG:phue:{"1":{"state": {"on":true,"bri":230,"hue":39458,"sat":254,"effect":"none","xy":[0.3691,0.5727],"alert":"none","colormode":"hs","reachable":true}, "type": "Color light", "name": "LivingColors 1", "modelid": "LLC011", "manufacturername": "Philips","uniqueid":"00:17:88:01:00:c1:35:b8-0b", "swversion": "66013452", "pointsymbol": { "1":"none", "2":"none", "3":"none", "4":"none", "5":"none", "6":"none",
 "7":"none", "8":"none" }},"2":{"state": {"on":true,"bri":230,"hue":39458,"sat":254,"effect":"none","xy":[0.1530,0.2414],"alert":"none","colormode":"hs","reachable":true}, "type": "Color light", "name": "LivingColors 2", "modelid": "LLC011", "manufacturername": "Philips","uniqueid":"00:17:88:01:00:c1:35:b7-0b", "swversion": "66013452", "pointsymbol": { "1":"none", "2":"none", "3":"none", "4":"none", "5":"none", "6":"none", "7":"none", "8":"none" }},"3":{"state": {"on":false,"bri":254,"alert":"none","reachable":false}, "type": "Dimmable light", "name": "Kitchen", "modelid": "ZLL Light", "manufacturername": "GE_Appliances","uniqueid":"7c:e5:24:00:00:15:33:a6-01", "swversion": "1197632", "pointsymbol": { "1":"none", "2":"none", "3":"none", "4":"none", "5":"none", "6":"none", "7":"none", "8":"none" }},"4":{"state": {"on":false,"bri":254,"alert":"none","reachable":false}, "type": "Dimmable light", "name": "Living Room Cabinet", "modelid": "ZLL Light", "manufacturername": "GE_Appliances","uniqueid":"7c:e5:24:00:00:13:71:d2-01", "swversion": "1197632", "pointsymbol": { "1":"none", "2":"none", "3":"none", "4":"none", "5":"none", "6":"none", "7":"none", "8":"none" }},"5":{"state": {"on":false,"bri":4,"alert":"select","reachable":false}, "type": "Dimmable light", "name": "Living Room Lamp", "modelid": "ZLL Light", "manufacturername": "GE_Appliances","uniqueid":"7c:e5:24:00:00:14:3d:65-01", "swversion": "1197632", "pointsymbol": { "1":"none", "2":"none", "3":"none", "4":"none", "5":"none", "6":"none", "7":"none", "8":"none" }},"6":{"state": {"on":false,"bri":254,"alert":"none","reachable":false}, "type": "Dimmable light", "name": "Library", "modelid": "ZLL Light", "manufacturername": "GE_Appliances","uniqueid":"7c:e5:24:00:00:13:6f:ee-01", "swversion": "1197632", "pointsymbol": { "1":"none", "2":"none", "3":"none", "4":"none", "5":"none", "6":"none", "7":"none", "8":"none" }},"7":{"state": {"on":false,"bri":0,"alert":"none","reachable":false}, "type": "Dimmable light", "name": "Work Lamp", "modelid": "ZLL Light", "manufacturername": "GE_Appliances","uniqueid":"7c:e5:24:00:00:11:13:41-01", "swversion": "1197632", "pointsymbol": { "1":"none", "2":"none", "3":"none", "4":"none", "5":"none", "6":"none", "7":"none", "8":"none" }},"8":{"state": {"on":false,"bri":1,"alert":"none","reachable":true}, "type": "Dimmable light", "name": "Zijian Lamp", "modelid": "ZLL Light", "manufacturername": "GE_Appliances","uniqueid":"7c:e5:24:00:00:13:88:fe-01", "swversion": "1197632", "pointsymbol": { "1":"none", "2":"none", "3":"none", "4":"none", "5":"none", "6":"none", "7":"none", "8":"none" }},"9":{"state": {"on":false,"bri":0,"alert":"none","reachable":false}, "type": "Dimmable light", "name": "Master Lamp", "modelid": "ZLL Light", "manufacturername": "GE_Appliances","uniqueid":"7c:e5:24:00:00:15:41:cb-01", "swversion": "1197632", "pointsymbol": { "1":"none", "2":"none", "3":"none", "4":"none", "5":"none", "6":"none", "7":"none", "8":"none" }},"10":{"state": {"on":false,"bri":2,"alert":"none","reachable":false}, "type": "Dimmable light", "name": "Studio Main", "modelid": "ZLL Light", "manufacturername": "GE_Appliances","uniqueid":"7c:e5:24:00:00:14:3e:1e-01", "swversion": "1197632", "pointsymbol": { "1":"none", "2":"none", "3":"none", "4":"none", "5":"none", "6":"none", "7":"none", "8":"none" }},"11":{"state": {"on":false,"bri":15,"alert":"none","reachable":false}, "type": "Dimmable light", "name": "Art Studio Main", "modelid": "ZLL Light", "manufacturername": "GE_Appliances","uniqueid":"7c:e5:24:00:00:15:43:4c-01", "swversion": "1197632", "pointsymbol": { "1":"none", "2":"none", "3":"none", "4":"none", "5":"none", "6":"none", "7":"none", "8":"none" }},"12":{"state": {"on":false,"bri":2,"alert":"none","reachable":false}, "type": "Dimmable light", "name": "Fireplace", "modelid": "ZLL Light", "manufacturername": "GE_Appliances","uniqueid":"7c:e5:24:00:00:12:af:b2-01", "swversion": "1197632", "pointsymbol": { "1":"none", "2":"none", "3":"none", "4":"none", "5":"none", "6":"none", "7":"none", "8":"none" }},"13":{"state": {"on":false,"bri":254,"hue":14922,"sat":144,"effect":"none","xy":[0.4595,0.4105],"ct":369,"alert":"none","colormode":"ct","reachable":true}, "type": "Extended color light", "name": "Master Lamp", "modelid": "LCT001", "manufacturername": "Philips","uniqueid":"00:17:88:01:00:ec:7e:ac-0b", "swversion": "66009663", "pointsymbol": { "1":"none", "2":"none", "3":"none", "4":"none", "5":"none", "6":"none", "7":"none", "8":"none" }},"14":{"state": {"on":true,"bri":230,"hue":39458,"sat":254,"effect":"none","xy":[0.4546,0.4684],"ct":359,"alert":"select","colormode":"hs","reachable":true}, "type": "Extended color light", "name": "Fireplace Spot", "modelid": "LCT001", "manufacturername": "Philips","uniqueid":"00:17:88:01:00:ee:9f:9c-0b", "swversion": "66009663", "pointsymbol": { "1":"none", "2":"none", "3":"none", "4":"none", "5":"none", "6":"none", "7":"none", "8":"none" }},"15":{"state": {"on":true,"bri":99,"hue":29727,"sat":244,"effect":"none","xy":[0.4546,0.4684],"ct":359,"alert":"select","colormode":"hs","reachable":true}, "type": "Extended color light", "name": "Studio Desk Lamp", "modelid": "LCT001", "manufacturername": "Philips","uniqueid":"00:17:88:01:00:ee:ad:96-0b", "swversion": "66009663", "pointsymbol": { "1":"none", "2":"none", "3":"none", "4":"none", "5":"none", "6":"none", "7":"none", "8":"none" }},"16":{"state": {"on":true,"bri":99,"hue":39458,"sat":244,"effect":"none","xy":[0.4546,0.4684],"ct":359,"alert":"select","colormode":"hs","reachable":true}, "type": "Extended color light", "name": "Studio Clip Lamp", "modelid": "LCT001", "manufacturername": "Philips","uniqueid":"00:17:88:01:00:ec:4f:48-0b", "swversion": "66009663", "pointsymbol": { "1":"none", "2":"none", "3":"none", "4":"none", "5":"none", "6":"none", "7":"none", "8":"none" }}}
DEBUG:phue:{'on': True}
DEBUG:phue:GET /api/1ef1d146dae80a72ad098aa21a675db/lights/ None
.
.
etc....
```

Here are the commands issued just immediately prior to failures, so far:

```
root@lie-pi5:/usr/local/src/raymond/hueslapper-0.0.1# cat hueslapper.log |grep -B3 "None"|grep -v swversion|less|grep PUT
DEBUG:phue:PUT /api/1ef1d146dae80a72ad098aa21a675db/lights/16/state {"transitiontime": 30, "hue": 29727}
DEBUG:phue:PUT /api/1ef1d146dae80a72ad098aa21a675db/lights/16/state {"transitiontime": 30, "hue": 39508}
DEBUG:phue:PUT /api/1ef1d146dae80a72ad098aa21a675db/lights/1/state {"transitiontime": 30, "bri": 192}
DEBUG:phue:PUT /api/1ef1d146dae80a72ad098aa21a675db/lights/14/state {"transitiontime": 30, "hue": 33924}
DEBUG:phue:PUT /api/1ef1d146dae80a72ad098aa21a675db/lights/16/state {"transitiontime": 30, "sat": 202}
DEBUG:phue:PUT /api/1ef1d146dae80a72ad098aa21a675db/lights/15/state {"transitiontime": 30, "sat": 227}
DEBUG:phue:PUT /api/1ef1d146dae80a72ad098aa21a675db/lights/15/state {"transitiontime": 30, "bri": 229}
DEBUG:phue:PUT /api/1ef1d146dae80a72ad098aa21a675db/lights/15/state {"transitiontime": 30, "sat": 215}
DEBUG:phue:PUT /api/1ef1d146dae80a72ad098aa21a675db/lights/16/state {"transitiontime": 30, "hue": 63313}
```

So, I don't think it's some sort of whacky values.  Those are all over the place.  Is there any way to make the debugging more verbose?  

The error is really originating from:

```
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''
```

Right?  I've googled a bit and found some discussion on a change in how user agents are used in httplib.  Could this have anything to do with it?

Looking through the httplib.py code a bit, I see:

```
class HTTPResponse:

    # strict: If true, raise BadStatusLine if the status line can't be
    # parsed as a valid HTTP/1.0 or 1.1 status line.  By default it is
    # false because it prevents clients from talking to HTTP/0.9
    # servers.  Note that a response with a sufficiently corrupted
    # status line will look like an HTTP/0.9 response.

    # See RFC 2616 sec 19.6 and RFC 1945 sec 6 for details.
```
There are many scenarios in which BadStatusLine is raised.  But, we are getting just a blank back, right?  Is that what ** httplib.BadStatusLine: '' ** means?  

```
        if not line:
            # Presumably, the server closed the connection before
            # sending a valid response.
            raise BadStatusLine(line)
```

So, if we are not getting a response back from the bridge... where all could the fault lie?  The bridge might be getting confused, right?  A possible bug in their web server.  Or, is there any timing involved on your end?  Does phue.py wait a certain amount of time for a response, then timeout if one is not received?  Maybe adjusting this timeout/signal upwards a bit would change things, if so?  

I apologize for my ignorance about it all.  I wish I understood better how this all works so that I could poke a few lines in here and there and try to figure this out.  I may still try to do that, but I will probably break something... hehheh.

**Comment by lleevveell66** [comment] 2015-05-23 21:06
I am going to try changing this:

```python
    def request(self, mode='GET', address=None, data=None):
        """ Utility function for HTTP GET/PUT requests for the API"""
        connection = httplib.HTTPConnection(self.ip, timeout=10)
```

to this:

```
    def request(self, mode='GET', address=None, data=None):
        """ Utility function for HTTP GET/PUT requests for the API"""
        connection = httplib.HTTPConnection(self.ip, timeout=30)
```

in the file:  /usr/local/lib/python2.7/dist-packages/phue-0.8-py2.7.egg/phue.py

**Comment by lleevveell66** [comment] 2015-05-23 21:24
Bleh.  Now, I get these:

```
Traceback (most recent call last):
  File "./hueslapper", line 34, in <module>
    light.hue=hue
  File "/usr/local/lib/python2.7/dist-packages/phue-0.8-py2.7.egg/phue.py", line 192, in hue
    self._set('hue', self._hue)
  File "/usr/local/lib/python2.7/dist-packages/phue-0.8-py2.7.egg/phue.py", line 106, in _set
    return self.bridge.set_light(self.light_id, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/phue-0.8-py2.7.egg/phue.py", line 684, in set_light
    converted_light) + '/state', json.dumps(data)))
  File "/usr/local/lib/python2.7/dist-packages/phue-0.8-py2.7.egg/phue.py", line 469, in request
    result = connection.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1034, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 407, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline()
  File "/usr/lib/python2.7/socket.py", line 430, in readline
    data = recv(1)
socket.timeout: timed out
Traceback (most recent call last):
  File "./hueslapper", line 11, in <module>
    light_names=b.get_light_objects('name')
  File "/usr/local/lib/python2.7/dist-packages/phue-0.8-py2.7.egg/phue.py", line 578, in get_light_objects
    lights = self.request('GET', '/api/' + self.username + '/lights/')
  File "/usr/local/lib/python2.7/dist-packages/phue-0.8-py2.7.egg/phue.py", line 474, in request
    result_str = result.read()
  File "/usr/lib/python2.7/httplib.py", line 546, in read
    s = self.fp.read()
  File "/usr/lib/python2.7/socket.py", line 351, in read
    data = self._sock.recv(rbufsize)
socket.error: [Errno 104] Connection reset by peer
```

The script does not stop, however.  Also, there is strange behavior, where instead of all lights transitioning at once to the new values, they are transitioning one-by-one, down the line.

**Comment by natcl** [comment] 2015-05-23 21:39
Is it possible you are sending too much data at once too quickly ? The bridge will rate limit api calls if you send too fast resulting in either slower update or no updates at all.


--
lecaude.com 
studioimaginaire.com

**Comment by lleevveell66** [comment] 2015-05-28 19:18
I posted the script.  Is that too much data sent too fast?  It's sent for 5 lights, every 4 seconds (transition of 3 seconds, then I wait 1 more for good measure).  Would it be better to send these all as a single command, somehow?

**Comment by natcl** [comment] 2015-05-29 01:09
It doesn't seem to be a lot of data.
I'll try running the script here to see if I get the same problem.

**Comment by G2Jose** [comment] 2016-02-07 00:21
Have the same issue. Have you had any luck resolving this?

**Comment by avzdk** [comment] 2016-05-19 05:26
Have the same issue.

**Comment by natcl** [comment] 2016-05-19 12:33
Post your script please. These errors are most likely related to network issues...

**Closed** 2017-07-02 17:38 UTC
